### PR TITLE
Add metadata into packages

### PR DESCRIPTION
**Pull request by hellcp**

### CODE REVIEW

**Comment by Sergeykot** [comment]
hi @hellcp 

I wanted to follow-up on this. Could you please give some explanation what exactly this PR does and why is it needed? Thanks

**Comment by jreidinger** [comment]
@Sergeykot beside some spec cleanup I think it is mostly related to appdata generation done in https://github.com/yast/yast-control-center/pull/43 .

**Comment by ngetahun** [comment]
@jreidinger Please fix the conflicts so we can go ahead with the merge.

**Comment by ngetahun** [comment]
Closing this since there's no response

**Pull request closed without merging**
