### PR TITLE
Handle Common Name length

### PR DESCRIPTION
**Pull request by jesusbv**

### CODE REVIEW

**Comment by lagartoflojo** [comment]
@jesusbv is this ready to be reviewed?

**Comment by ikapelyukhin** [comment]
> @jesusbv is this ready to be reviewed?

Let's hold off for a bit.

At the moment common name length is very low (36 characters), that's because we use `string_mask = utf8only`. This seems to be the recommended setting in the current millennium, though (openssl documentation states: `If the utf8only option is used then only UTF8Strings will be used: this is the PKIX recommendation in RFC2459 after 2003.`) For ASCII-encoded string the limit would have been 64 bytes.

However, I gravitate towards dropping common name completely and using just the subjectAltNames instead. AFAIK, it's an older standard from the times when the dinosaurs have roamed the earth and it was possible to have only one domain name/IP in the certificate.

subjectAltName is a X.509 extension that come later, it should support strings up to 256 bytes. Modern-day versions of openssl should support certs with an empty common name but with at least one valid subjectAltName.

[RFC2818][1] states: "Although the use of the Common Name is existing practice, it is deprecated and Certification Authorities are encouraged to use the dNSName instead." (and that RFC is from the year 2000 :facepalm: ) The reason why we ended up having common name in Yast RMT is that `yast_ca_mgm` had it -- the nuance of CN and subjectAltName wasn't obvious to me at the time when I was porting it to Ruby.

So far I've asked Jesus to generate some certs with an empty CN and some valid subjectAltNames -- we'll test that it doesn't cause any issues on openssl version shipped with SLES 12 GA. If that's the case, we'll move forward with dropping the CN field.

[1]: https://tools.ietf.org/html/rfc2818

**Comment by lagartoflojo** [comment]
Thanks for the detailed explanation @ikapelyukhin! It will definitely help our future selves to have all of that documented =) Let us know if you need any help from us.

**Comment by lagartoflojo** [comment]
Please let us know when / if you want this reviewed by the SCC team. Thanks!

**Comment by jesusbv** [comment]
@lagartoflojo please, feel free to review it at any time

**Comment by ikapelyukhin** [comment]
> At the moment common name length is very low (36 characters), that's because we use `string_mask = utf8only`. This seems to be the recommended setting in the current millennium, though (openssl documentation states: `If the utf8only option is used then only UTF8Strings will be used: this is the PKIX recommendation in RFC2459 after 2003.`) For ASCII-encoded string the limit would have been 64 bytes.

Disregard this paragraph, this was a red herring :fish: Common name length is 64 characters long regardless of the encoding, the issue was actually caused by this during CA cert generation:

https://github.com/yast/yast-rmt/blob/3f0dda7262076f762073a70e8b6f29770f0a0cea/src/lib/rmt/ssl/config_generator.rb#L29

Length of "RMT Certificate Authority ()" string is 28, 64 - 28 = 36 characters left for the hostname. The easy fix for now is to not append the hostname to the CA common name.

I think it's still a good idea to switch to subjectAltNames to increase the limit to 256 characters, but that's more time consuming, for now I'll file an issue with the description of needs to be done.

**Comment by jesusbv** [comment]
Hi @lagartoflojo 

Please, let me know if the PR needs anything in order to be reviewed.

**Comment by lagartoflojo** [comment]
I created a [card in Trello](https://trello.com/c/v507gCx1/3904-review-yast2-rmt-prevent-failure-with-long-common-name-when-generating-ssl-certs) for this, to feed it into our kanban process =)

**Pull request merged**
