### PR TITLE
Remove newline and remove database password label

### PR DESCRIPTION
**Pull request by felixsch**

### CODE REVIEW

**Comment by ikapelyukhin** [comment]
Make the coverage great again! :grimacing:

**Comment by fschueller** [comment]
I wonder how that decreased with these changes though.

**Comment by ikapelyukhin** [comment]
Yeah, that's weird. Maybe something changed in the Yast modules?

**Comment by ikapelyukhin** [comment]
I've triggered rebuild on Travis.

**Comment by ikapelyukhin** [comment]
Oh no, the specs are failing: `uninitialized constant Yast::SystemdService`. Yeah, something's up.

**Comment by fschueller** [comment]
So much fun. :-/

**Comment by ikapelyukhin** [comment]
Tests are running in a Docker container based on `yastdevel/ruby` image, fixing might be as simple as locking the version in the Dockerfile.
Although it is worth asking Yast team what's up with `Yast::SystemdService` in the most recent version.

**Comment by felixsch** [comment]
I changed the dockerfile to fetch from the `sle15` branch instead of latest master

**Pull request merged**
